input_boolean:
  heating_enabled:
    name: 'AC : Chauffage'
    icon: mdi:fire
  cooling_enabled:
    name: 'AC : Refroidissement'
    icon: mdi:snowflake

  homeoffice:
    name: Home Office
    icon: mdi:toggle-switch
  to_sleep:
    name: To Sleep
    icon: mdi:toggle-switch
  to_away:
    name: To Away
    icon: mdi:toggle-switch


  thermostats_on_off:
    name: 'Chauffage : On / Off'
    icon: mdi:thermostat-box

  thermostats_away:
    name: 'Chauffage : Mode Absent'
    icon: mdi:thermostat-box

  thermostats_ac_on_off:
      name: 'AC : On / Off'
      icon: mdi:thermostat-box



input_number:
  off_temperature:
    name: Off Température
    min: 14
    max: 36
    step: 1.0
    unit_of_measurement: °C
    icon: 'mdi:thermometer-lines'
  off_temperature_convecteur:
    name: Off Température Convecteur
    min: 6
    max: 16
    step: 1.0
    unit_of_measurement: °C
    icon: 'mdi:thermometer-lines'    
  off_temperature_ac:
    name: Off Température AC
    min: 14
    max: 30
    step: 1.0
    unit_of_measurement: °C
    icon: 'mdi:thermometer-lines'  



binary_sensor:
  - platform: template
    sensors:
      workday_saturday_working:
        friendly_name: "Samedi travaillé"
        value_template: >
          {% if now().isoweekday() in (5,) and states.binary_sensor.workday_sensor.state == 'on' %}
            true
          {%else%}
            false
          {% endif %}

automation:
  - alias: 'CLIMATE - On / Off des Thermostats'
    description: ''
    trigger:
    - platform: state
      entity_id: input_boolean.thermostats_on_off
    action:
    - service: climate.set_hvac_mode
      entity_id: climate.climate_all
      data_template:
        hvac_mode: >
          {% if states.input_boolean.thermostats_on_off.state == "on" %}
            heat
          {% else %}
            off
          {% endif %}

  - alias: 'CLIMATE - Away / None des Thermostats'
    description: ''
    trigger:
    - platform: state
      entity_id: input_boolean.thermostats_away
    action:
    - service: climate.set_preset_mode
      entity_id: climate.climate_all
      data_template:
        preset_mode: >
          {% if states.input_boolean.thermostats_away.state == "on" %}
            away
          {% else %}
            none
          {% endif %}

# AC
  - id: 'd1bdf1ac-4d43-4f04-9b09-03e7a5e9ff59'
    alias: 'CLIMATE - AC Chaud'
    description: ''
    trigger:
      - platform: state
        entity_id: input_boolean.heating_enabled
        to: 'on'
      - platform: state
        entity_id: climate.daikin
        # attribute: hvac_mode
        to: 'heat'
    action:
    - service: input_boolean.turn_off
      target:
        entity_id: input_boolean.cooling_enabled
    - service: input_boolean.turn_on
      target:
        entity_id: input_boolean.heating_enabled
    - service: climate.set_hvac_mode
      target:
        entity_id: climate.daikin
      data:
        hvac_mode: heat

  - id: '8fbf1387-04db-44e8-a210-472e4ff80501'
    alias: 'CLIMATE - AC Froid'
    description: ''
    trigger:
      - platform: state
        entity_id: input_boolean.cooling_enabled
        to: 'on'
      - platform: state
        entity_id: climate.daikin
        # attribute: hvac_mode
        to: 'cool'
    action:
    - service: input_boolean.turn_off
      target:
        entity_id: input_boolean.heating_enabled
    - service: input_boolean.turn_on
      target:
        entity_id: input_boolean.cooling_enabled
    - service: climate.set_hvac_mode
      target:
        entity_id: climate.daikin
      data:
        hvac_mode: cool
