# SEMAINE
input_datetime:
  heating_cuisine_start_1:
    name: "Confort : Début"
    has_date: false
    has_time: true
  heating_cuisine_end_1:
    name: "Confort : Fin"
    has_date: false
    has_time: true
  heating_cuisine_start_2:
    name: "Confort : Début"
    has_date: false
    has_time: true
  heating_cuisine_end_2:
    name: "Confort : Fin"
    has_date: false
    has_time: true
  heating_cuisine_start_3:
    name: "Confort : Début"
    has_date: false
    has_time: true
  heating_cuisine_end_3:
    name: "Confort : Fin"
    has_date: false
    has_time: true
  heating_cuisine_start_4:
    name: "Confort : Début"
    has_date: false
    has_time: true
  heating_cuisine_end_4:
    name: "Confort : Fin"
    has_date: false
    has_time: true

# WE
  heating_cuisine_start_1_d:
    name: "Confort : Début"
    has_date: false
    has_time: true
  heating_cuisine_end_1_d:
    name: "Confort : Fin"
    has_date: false
    has_time: true
  heating_cuisine_start_2_d:
    name: "Confort : Début"
    has_date: false
    has_time: true
  heating_cuisine_end_2_d:
    name: "Confort : Fin"
    has_date: false
    has_time: true
  heating_cuisine_start_3_d:
    name: "Confort : Début"
    has_date: false
    has_time: true
  heating_cuisine_end_3_d:
    name: "Confort : Fin"
    has_date: false
    has_time: true
  heating_cuisine_start_4_d:
    name: "Confort : Début"
    has_date: false
    has_time: true
  heating_cuisine_end_4_d:
    name: "Confort : Fin"
    has_date: false
    has_time: true    

# PRESENCE
  next_cuisine_start:
    name: Arrivé Cuisine / Hall / Bureau
    has_date: true
    has_time: true
    icon: mdi:calendar-clock
  next_cuisine_stop:
    name: Départ Cuisine / Hall / Bureau
    has_date: true
    has_time: true
    icon: mdi:calendar-clock


binary_sensor:
  - platform: template
    sensors:
      heating_cuisine_1: # SEMAINE
        entity_id: sensor.time
        friendly_name: Mode Confort
        value_template: >
          {% set t = states('sensor.time') %}
          {% set start = states('input_datetime.heating_cuisine_start_1') [0:5] %}
          {% set stop = states('input_datetime.heating_cuisine_end_1') [0:5] %}
          {{ (start <= t < stop if start < stop else (start <= t or t < stop)) == true 
            and states('binary_sensor.workday_sensor') == 'on'
            and states('input_boolean.presence_cuisine') == 'on' 
            and states('input_boolean.heating_cuisine_enabled_1') == 'on' }}
      heating_cuisine_2:
        entity_id: sensor.time
        friendly_name: Mode Confort
        value_template: >
          {% set t = states('sensor.time') %}
          {% set start = states('input_datetime.heating_cuisine_start_2') [0:5] %}
          {% set stop = states('input_datetime.heating_cuisine_end_2') [0:5] %}
          {{ (start <= t < stop if start < stop else (start <= t or t < stop)) == true
            and states('binary_sensor.workday_sensor') == 'on'
            and states('input_boolean.presence_cuisine') == 'on' 
            and states('input_boolean.heating_cuisine_enabled_2') == 'on' }}
      heating_cuisine_3:
        entity_id: sensor.time
        friendly_name: Mode Confort
        value_template: >
          {% set t = states('sensor.time') %}
          {% set start = states('input_datetime.heating_cuisine_start_3') [0:5] %}
          {% set stop = states('input_datetime.heating_cuisine_end_3') [0:5] %}
          {{ (start <= t < stop if start < stop else (start <= t or t < stop)) == true
            and states('binary_sensor.workday_sensor') == 'on'
            and states('input_boolean.presence_cuisine') == 'on' 
            and states('input_boolean.heating_cuisine_enabled_3') == 'on' }}
      heating_cuisine_4:
        entity_id: sensor.time
        friendly_name: Mode Confort
        value_template: >
          {% set t = states('sensor.time') %}
          {% set start = states('input_datetime.heating_cuisine_start_4') [0:5] %}
          {% set stop = states('input_datetime.heating_cuisine_end_4') [0:5] %}
          {{ (start <= t < stop if start < stop else (start <= t or t < stop)) == true
            and states('binary_sensor.workday_sensor') == 'on'
            and states('input_boolean.presence_cuisine') == 'on' 
            and states('input_boolean.heating_cuisine_enabled_4') == 'on' }}

      heating_cuisine_1_d: # DIMANCHE
        entity_id: sensor.time
        friendly_name: Mode Confort
        value_template: >
          {% set t = states('sensor.time') %}
          {% set start = states('input_datetime.heating_cuisine_start_1_d') [0:5] %}
          {% set stop = states('input_datetime.heating_cuisine_end_1_d') [0:5] %}
          {{ (start <= t < stop if start < stop else (start <= t or t < stop)) == true
            and states('binary_sensor.workday_sensor') ==  'off' 
            and states('input_boolean.presence_cuisine') == 'on' 
            and states('input_boolean.heating_cuisine_enabled_1_d') == 'on' }}
      heating_cuisine_2_d:
        entity_id: sensor.time
        friendly_name: Mode Confort
        value_template: >
          {% set t = states('sensor.time') %}
          {% set start = states('input_datetime.heating_cuisine_start_2_d') [0:5] %}
          {% set stop = states('input_datetime.heating_cuisine_end_2_d') [0:5] %}
          {{ (start <= t < stop if start < stop else (start <= t or t < stop)) == true 
            and states('binary_sensor.workday_sensor') ==  'off'
            and states('input_boolean.presence_cuisine') == 'on' 
            and states('input_boolean.heating_cuisine_enabled_2_d') == 'on' }}
      heating_cuisine_3_d:
        entity_id: sensor.time
        friendly_name: Mode Confort
        value_template: >
          {% set t = states('sensor.time') %}
          {% set start = states('input_datetime.heating_cuisine_start_3_d') [0:5] %}
          {% set stop = states('input_datetime.heating_cuisine_end_3_d') [0:5] %}
          {{ (start <= t < stop if start < stop else (start <= t or t < stop)) == true 
            and states('binary_sensor.workday_sensor') ==  'off'
            and states('input_boolean.presence_cuisine') == 'on' 
            and states('input_boolean.heating_cuisine_enabled_3_d') == 'on' }}
      heating_cuisine_4_d:
        entity_id: sensor.time
        friendly_name: Mode Confort
        value_template: >
          {% set t = states('sensor.time') %}
          {% set start = states('input_datetime.heating_cuisine_start_4_d') [0:5] %}
          {% set stop = states('input_datetime.heating_cuisine_end_4_d') [0:5] %}
          {{ (start <= t < stop if start < stop else (start <= t or t < stop)) == true
            and states('binary_sensor.workday_sensor') ==  'off'
            and states('input_boolean.presence_cuisine') == 'on' 
            and states('input_boolean.heating_cuisine_enabled_4_d') == 'on' }}




  - platform: template
    sensors:
      cuisine_window_delayed:
        friendly_name: "Fenêtre (delayed)"
        device_class: window
        #window_room: bedroom
        delay_on: 
          seconds: 300
        delay_off:
          seconds: 300
        value_template: >-
          {{ is_state('binary_sensor.fenetre_cuisine', 'on') }}
        icon_template: >-
          {% if is_state('binary_sensor.fenetre_cuisine', 'on') %}
            mdi:window-open
          {% else %}
            mdi:window-closed
          {% endif %}  


# script:
#   heating_cuisine_boost:
#     alias: Boost
#     icon: mdi:timer-outline
#     sequence:
#     - event: schedy_set_value
#       event_data:
#         app_name: schedy_heating
#         room: cuisine
#         v: '{{ states.input_number.heating_cuisine_temperature_boost.state }}'
#         rescheduling_delay: '{{ states.input_number.heating_cuisine_time_boost.state }}'

#   heating_cuisine_boost_reset:
#     alias: "Boost : Reset"
#     icon: mdi:timer-off-outline
#     sequence:
#     - event: schedy_set_value
#       event_data:
#         app_name: schedy_heating
#         room: cuisine
#         v:  20
#         rescheduling_delay: 1


sensor: 
  - platform: template 
    sensors:
      average_cuisine_temp:  # On fait la moyenne des 3 capteurs pour l'affichage
        friendly_name: 'CHB Température'
        unit_of_measurement: "°C"
        value_template: >-
          {{ (float(states.sensor.mi_cuisine_temp.state) + float(states.sensor.mi_bureau_temp.state) + float(states.sensor.rpi_mi_t_hall.state)) / 3 | round(2) }}
      average_cuisine_hum:
        friendly_name: 'CHB Humidité'
        unit_of_measurement: "%"
        value_template: >-
          {{ (float(states.sensor.mi_cuisine_hum.state) + float(states.sensor.mi_bureau_hum.state) + float(states.sensor.rpi_mi_h_hall.state)) / 3 | round(2) }}


input_number:
  # heating_cuisine_temperature_boost: # BOOST
  #   name: 'Boost : Température'
  #   min: 12
  #   max: 25
  #   step: 0.5
  #   unit_of_measurement: °C
  #   icon: 'mdi:thermometer-lines'
  # heating_cuisine_time_boost:
  #   name: 'Boost : Durée'
  #   initial: 60
  #   min: 5
  #   max: 360
  #   step: 5
  #   unit_of_measurement: Min.
  #   icon: 'mdi:clock'

  heating_cuisine_temperature_confort_1: # SEMAINE
    name: 'Température : Confort'
    min: 12
    max: 25
    step: 0.5
    unit_of_measurement: °C
    icon: 'mdi:thermometer-lines'
  heating_cuisine_temperature_confort_2:
    name: 'Température : Confort'
    min: 12
    max: 25
    step: 0.5
    unit_of_measurement: °C
    icon: 'mdi:thermometer-lines'
  heating_cuisine_temperature_confort_3:
    name: 'Température : Confort'
    min: 12
    max: 25
    step: 0.5
    unit_of_measurement: °C
    icon: 'mdi:thermometer-lines'
  heating_cuisine_temperature_confort_4:
    name: 'Température : Confort'
    min: 12
    max: 25
    step: 0.5
    unit_of_measurement: °C
    icon: 'mdi:thermometer-lines'

  heating_cuisine_temperature_confort_1_d: # DIMANCHE
    name: 'Température : Confort'
    min: 12
    max: 25
    step: 0.5
    unit_of_measurement: °C
    icon: 'mdi:thermometer-lines'
  heating_cuisine_temperature_confort_2_d:
    name: 'Température : Confort'
    min: 12
    max: 25
    step: 0.5
    unit_of_measurement: °C
    icon: 'mdi:thermometer-lines'
  heating_cuisine_temperature_confort_3_d:
    name: 'Température : Confort'
    min: 12
    max: 25
    step: 0.5
    unit_of_measurement: °C
    icon: 'mdi:thermometer-lines'
  heating_cuisine_temperature_confort_4_d:
    name: 'Température : Confort'
    min: 12
    max: 25
    step: 0.5
    unit_of_measurement: °C
    icon: 'mdi:thermometer-lines'



  heating_cuisine_temperature_eco:
    name: 'Température : Eco'
    min: 12
    max: 25
    step: 0.5
    unit_of_measurement: °C
    icon: 'mdi:thermometer-lines'
  heating_cuisine_temperature_away:
    name: 'Température : Absence'
    min: 12
    max: 25
    step: 0.5
    unit_of_measurement: °C
    icon: 'mdi:thermometer-lines'


input_boolean:
  heating_cuisine_enabled_1: #SEMAINE
    name: Plage Active
    icon: mdi:toggle-switch
  heating_cuisine_enabled_2:
    name: Plage Active
    icon: mdi:toggle-switch
  heating_cuisine_enabled_3:
    name: Plage Active
    icon: mdi:toggle-switch
  heating_cuisine_enabled_4:
    name: Plage Active
    icon: mdi:toggle-switch


  heating_cuisine_enabled_1_d: # DIMANCHE
    name: Plage Active
    icon: mdi:toggle-switch
  heating_cuisine_enabled_2_d:
    name: Plage Active
    icon: mdi:toggle-switch
  heating_cuisine_enabled_3_d:
    name: Plage Active
    icon: mdi:toggle-switch
  heating_cuisine_enabled_4_d:
    name: Plage Active
    icon: mdi:toggle-switch

  presence_cuisine:
    name: Présence Cuisine / Hall / Bureau
#    initial: off
    icon: mdi:account-check

automation:
- alias: 'Schedy : Cuisine / Hall / Bureau (Arrivée)'
  trigger:
  - platform: state
    entity_id: input_boolean.presence_cuisine
    to: 'on'
  - platform: template # Date de début de présence
    value_template: "{{ states('sensor.date_time') == (states.input_datetime.next_cuisine_start.attributes.timestamp | int | timestamp_custom('%Y-%m-%d, %H:%M', True)) }}"
  condition: []
  action:
  - service: input_boolean.turn_on
    data: {}
    target:
      entity_id: input_boolean.presence_cuisine
  - service: notify.slack_hass_canaletto
    data:
      message: "{{now().strftime('%d/%m/%Y, %H:%M')}} > Arrivée Cuisine / Hall / Bureau | Température Cuisine / Hall / Bureau : {{ states('sensor.mi_cuisine_temp') }}°"

- alias: 'Schedy : Cuisine / Hall / Bureau (départ)'
  trigger:
  - platform: state
    entity_id: input_boolean.presence_cuisine
    to: 'off'
  - platform: template # Date de fin de présence
    value_template: "{{ states('sensor.date_time') == (states.input_datetime.next_cuisine_stop.attributes.timestamp | int | timestamp_custom('%Y-%m-%d, %H:%M', True)) }}"
  condition: []
  action:
  - service: input_boolean.turn_off
    data: {}
    target:
      entity_id: input_boolean.presence_cuisine
  - service: notify.slack_hass_canaletto
    data:
      message: "{{now().strftime('%d/%m/%Y, %H:%M')}} > Départ Cuisine / Hall / Bureau | Température Cuisine / Hall / Bureau : {{ states('sensor.mi_cuisine_temp') }}°"
   
