# auto:
# - alias: 'TEST Lionel'
#   id: 89fc5a67-94f9-45e7-a075-0024368442a7
#   initial_state: true
#   mode: parallel
#   trigger:
#     - platform: state
#       entity_id: binary_sensor.heating_ac_1
#       to: 'on'
#     - platform: state
#       entity_id: binary_sensor.heating_ac_12
#       to: 'on'
#   variables:
#     heating_value: >
#       {% set input_temp = {
#         'binary_sensor.heating_ac_1':'input_number.heating_ac_1',
#         'binary_sensor.heating_ac_2':'input_number.heating_ac_2'
#         }
#         %}          
#       {{ input_temp[trigger.entity_id] }}
#   action:
#     - service: climate.set_temperature
#       target:
#         entity_id: climate_daikin
#       data:
#         temperature: {{ heating_value }}

input_select:
  comfort_ac:
    name: Modes du climatiseur # hvac_modes: fan_only, dry, cool, heat, heat_cool, off
    icon: mdi:form-select
    options:
      - Refroidissement
      - Chauffage
      - Manuel
      - "Off"

automation:
- id: 0ff7454c-4592-4479-b2ae-40eaf3043853
  description: Comfort - AC
  alias: "Comfort - AC"
  mode: restart
  trigger:
    - platform: time_pattern
      minutes: "/10"
  condition:
    - condition: state
      entity_id: input_boolean.thermostats_ac_on_off
      state: "on"
    - condition: state
      entity_id: binary_sensor.life_windows_and_doors_delayed
      state: "off "
  action:
    - condition: "{{ not states('input_select.comfort_ac') in ('Manuel', 'Off') }}"
    - choose:
        # - conditions: # COOL OFF
        #     - "{{ is_state('input_boolean.thermostats_away', 'on') or is_state('input_boolean.to_away', 'on') or is_state('input_boolean.to_sleep', 'on') is_state('binary_sensor.lionel_geo', 'off') }}" 
        #     - "{{ is_state('input_boolean.cooling_enabled', 'on') }}"

        - conditions: # COOL OFF
            - condition: or
              conditions:
                - "{{ is_state('input_boolean.thermostats_away', 'on') }}"
                - "{{ is_state('input_boolean.to_away', 'on') }}"
                # - "{{ is_state('input_boolean.to_sleep', 'on') }}"
                - "{{ is_state('binary_sensor.lionel_geo', 'off') }}" # input_boolean.presence_lionel_geo        input_select.comfort_ac
            - condition: 
                # - "{{ is_state('input_boolean.cooling_enabled', 'on') }}"
                - "{{ is_state('input_select.comfort_ac', 'Refroidissement') }}"
          sequence:
            - service: climate.set_hvac_mode
              data:
                hvac_mode: 'off'
              target:
                entity_id: climate.daikin

        - conditions: # COOL SLEEP
            - "{{ is_state('input_boolean.to_sleep', 'on') }}"
            - "{{ is_state('input_select.comfort_ac', 'Refroidissement') }}"
          sequence:
            - service: climate.set_hvac_mode
              data:
                hvac_mode: 'cool'
              target:
                entity_id: climate.daikin
            - service: climate.set_temperature
              data:
                temperature: "{{ states('input_number.heating_ac_temperature_eco') }}"
              target:
                entity_id: climate.daikin                

        - conditions: # HEAT ECO
            - condition: or
              conditions:
                - "{{ is_state('input_boolean.to_away', 'on') }}"
                - "{{ is_state('input_boolean.to_sleep', 'on') }}"
                - "{{ is_state('binary_sensor.lionel_geo', 'off') }}" # input_boolean.presence_lionel_geo
            - condition: 
                - "{{ is_state('input_select.comfort_ac', 'Chauffage') }}"
          sequence:
            - service: climate.set_hvac_mode
              data:
                hvac_mode: 'heat'
              target:
                entity_id: climate.daikin
            - service: climate.set_temperature
              data:
                temperature: "{{ states('input_number.heating_ac_temperature_eco') }}"
              target:
                entity_id: climate.daikin

        - conditions: # HEAT AWAY
            - "{{ is_state('input_boolean.thermostats_away', 'on') }}"
            - "{{ is_state('input_select.comfort_ac', 'Chauffage') }}"
          sequence:
            - service: climate.set_hvac_mode
              data:
                hvac_mode: 'heat'
              target:
                entity_id: climate.daikin
            - service: climate.set_temperature
              data:
                temperature: "{{ states('input_number.heating_ac_temperature_away') }}"
              target:
                entity_id: climate.daikin

# Plages horaires
        - conditions: "{{ is_state('binary_sensor.heating_ac_1', 'on') }}"
          sequence:
            - service: climate.set_temperature
              data:
                temperature: "{{ states('input_number.heating_ac_temperature_confort_1') }}"
              target:
                entity_id: climate.daikin
        - conditions: "{{ is_state('binary_sensor.heating_ac_2', 'on') }}"
          sequence:
            - service: climate.set_temperature
              data:
                temperature: "{{ states('input_number.heating_ac_temperature_confort_2') }}"
              target:
                entity_id: climate.daikin
        - conditions: "{{ is_state('binary_sensor.heating_ac_3', 'on') }}"
          sequence:
            - service: climate.set_temperature
              data:
                temperature: "{{ states('input_number.heating_ac_temperature_confort_3') }}"
              target:
                entity_id: climate.daikin
        - conditions: "{{ is_state('binary_sensor.heating_ac_4', 'on') }}"
          sequence:
            - service: climate.set_temperature
              data:
                temperature: "{{ states('input_number.heating_ac_temperature_confort_4') }}"
              target:
                entity_id: climate.daikin

        - conditions: "{{ is_state('binary_sensor.heating_ac_1_d', 'on') }}"
          sequence:
            - service: climate.set_temperature
              data:
                temperature: "{{ states('input_number.heating_ac_temperature_confort_1_d') }}"
              target:
                entity_id: climate.daikin
        - conditions: "{{ is_state('binary_sensor.heating_ac_2_d', 'on') }}"
          sequence:
            - service: climate.set_temperature
              data:
                temperature: "{{ states('input_number.heating_ac_temperature_confort_2_d') }}"
              target:
                entity_id: climate.daikin
        - conditions: "{{ is_state('binary_sensor.heating_ac_3_d', 'on') }}"
          sequence:
            - service: climate.set_temperature
              data:
                temperature: "{{ states('input_number.heating_ac_temperature_confort_3_d') }}"
              target:
                entity_id: climate.daikin
        - conditions: "{{ is_state('binary_sensor.heating_ac_4_d', 'on') }}"
          sequence:
            - service: climate.set_temperature
              data:
                temperature: "{{ states('input_number.heating_ac_temperature_confort_4_d') }}"
              target:
                entity_id: climate.daikin


      default:
        - choose:
            - conditions:
                # - "{{ is_state('input_boolean.thermostats_on_off', 'on') }}" # chauffage on
              sequence:
                - service: climate.set_temperature
                  data:
                    temperature: "{{ states('input_number.heating_ac_temperature_eco') }}"
                  target:
                    entity_id: climate.daikin




- id: 56ee275e-3f52-4d88-a862-5e21f5708a82
  description: Comfort - AC - Immediate
  alias: "Comfort - AC - Immediate"
  mode: restart
  trigger:
    - platform: state
      entity_id:
        - input_number.heating_ac_temperature_confort_1
        - input_number.heating_ac_temperature_confort_2
        - input_number.heating_ac_temperature_confort_3
        - input_number.heating_ac_temperature_confort_4
        - input_number.heating_ac_temperature_confort_1_d
        - input_number.heating_ac_temperature_confort_2_d
        - input_number.heating_ac_temperature_confort_3_d
        - input_number.heating_ac_temperature_confort_4_d
        - input_number.heating_ac_temperature_eco
        - input_number.heating_ac_temperature_away
        - binary_sensor.heating_ac_1
        - binary_sensor.heating_ac_2
        - binary_sensor.heating_ac_3
        - binary_sensor.heating_ac_4
        - binary_sensor.heating_ac_1_d
        - binary_sensor.heating_ac_2_d
        - binary_sensor.heating_ac_3_d
        - binary_sensor.heating_ac_4_d
        - input_boolean.to_away
        - binary_sensor.life_windows_and_doors_delayed
        - input_boolean.presence_ac
        - input_boolean.to_sleep # eco heat off cool
        - input_boolean.heating_enabled
        - input_boolean.cooling_enabled
        - input_boolean.thermostats_ac_on_off
        - binary_sensor.lionel_geo # eco heat off cool
        - input_boolean.thermostats_away
        - input_select.comfort_ac

  condition:
    # - condition: state # periode chauffage ou clim
    #   entity_id: input_boolean.thermostats_ac_on_off
    #   state: "on"
  action:
    - choose:
        - conditions:
            - condition: or
              conditions:
                - "{{ is_state('binary_sensor.life_windows_and_doors_delayed', 'on') }}"
                # - "{{ is_state('input_boolean.thermostats_ac_on_off', 'off') }}"
                - "{{ is_state('input_select.comfort_ac', 'Off') }}"
          sequence:
            - service: climate.set_hvac_mode
              data:
                hvac_mode: 'off'
              target:
                entity_id: climate.daikin

      default:
        - choose:
            - conditions: "{{ is_state('input_select.comfort_ac', 'Refroidissement') }}"
              sequence:
                - service: climate.set_hvac_mode
                  data:
                    hvac_mode: 'cool'
                  target:
                    entity_id: climate.daikin
                - service: automation.trigger
                  target:
                    entity_id: "automation.comfort_ac"

            - conditions: "{{ is_state('input_select.comfort_ac', 'Chauffage') }}"
              sequence:
                - service: climate.set_hvac_mode
                  data:
                    hvac_mode: 'heat'
                  target:
                    entity_id: climate.daikin
                - service: automation.trigger
                  target:
                    entity_id: "automation.comfort_ac"



