binary_sensor:

template:
  - binary_sensor:
      - name: VR - Baie - Running
        state: "{{ not is_state('input_select.vr_baie_immediate', 'Manuel') }}"
        device_class: running

input_select:
  vr_baie_immediate:
    name: Gestion de vr_baie
    icon: mdi:form-select
    options:
      - Automatique
      - Manuel
      - Entrouvert

input_datetime:
  vr_baie_duration:
    name: Délai avant suspension
    has_date: false
    has_time: true

input_number:
  vr_baie_detection:
    name: Délai (s) avant suspension
    min: "5"
    max: "600"
    step: "5"
    unit_of_measurement: "'"
    icon: mdi:clock-edit-outline
  # vr_baie_duration:
  #   name: Durée (min) de la suspension
  #   min: "1"
  #   max: "1440"
  #   step: "1"
  #   unit_of_measurement: "''"
  #   icon: mdi:clock-edit-outline
  vr_baie_planned_position:
    name: Position désirée
    min: "-1"
    max: "100"
    step: "1"
    unit_of_measurement: "%"

timer:
  vr_baie:
    name: Durée de suspension restant
    restore: true
input_text:
  # vr_baie_suspend:
  #   name: Fin de suspension du volet roulant
  #   max: 255
  #   icon: mdi:information-outline
  vr_baie_condition:
    name: Condition du dernier automatisme
    max: 100
    icon: mdi:information-outline

automation:
- id: e1726dd0-4907-403c-83e2-d10f1aeb8608
  description: VR Baie - Position
  alias: "VR Baie - Position"
  mode: restart
  trigger:
    - platform: time_pattern
      minutes: "/10" # Durée entre chaque calcul de positionnement
    - platform: event
      event_type:
        - timer.cancelled
        - timer.finished
      event_data:
        entity_id: timer.vr_baie      
  condition:
    - condition: state # Le volet ne doit pas être déjà en cours de suspension
      entity_id: timer.vr_baie
      state: "idle"
    - condition: template # La position réelle du volet doit avoir changé depuis plus de "vr_baie_detection" secondes
      value_template: "{{ (as_timestamp(now()) - as_timestamp(states.cover.vr_baie.last_changed) | int(0)) > (states('input_number.vr_baie_detection') | int) }}"
  action:
    - condition: template # Le volet ne doit pas être en mode "Manuel"
      value_template: "{{ not is_state('input_select.vr_baie_immediate', 'Manuel') }}"
    - choose: # On vérifie si une condition immédiate correspond
        - conditions:
            - condition: state
              entity_id: input_boolean.alarmo_armed_vacation
              state: "on"
          sequence:
            - service: input_number.set_value
              target:
                entity_id: input_number.vr_baie_planned_position
              data:
                value: 0
            - service: input_text.set_value
              target:
                entity_id: input_text.vr_baie_condition
              data:
                value: "Condition : Alarmo Vacation - 0 %"
        - conditions:
            - condition: state
              entity_id: input_boolean.alarmo_armed_away
              state: "on"
          sequence:
            - service: input_number.set_value
              target:
                entity_id: input_number.vr_baie_planned_position
              data:
                value: 0
            - service: input_text.set_value
              target:
                entity_id: input_text.vr_baie_condition
              data:
                value: "Condition : Alarmo Away - 0 %"

        - conditions: 
            - "{{ as_timestamp(states('input_button.lionel_down'))|timestamp_custom('%H:%M', true) == states('sensor.time')  }}"
          sequence:
            - service: input_number.set_value
              target:
                entity_id: input_number.vr_baie_planned_position
              data:
                value: "0"
            - service: input_text.set_value
              target:
                entity_id: input_text.vr_baie_condition
              data:
                value: "Condition : Bonne Nuit (coucher) - 0 %"

        - conditions:
            - "{{ as_timestamp(states('input_button.lionel_up'))|timestamp_custom('%H:%M', true) == states('sensor.time')  }}"
          sequence:
            - service: input_number.set_value
              target:
                entity_id: input_number.vr_baie_planned_position
              data:
                value: "93"
            - service: input_text.set_value
              target:
                entity_id: input_text.vr_baie_condition
              data:
                value: "Condition : Bonjour (lever) - 93 %"

        - conditions:
            - condition: state
              entity_id: switch.lidl_multiprise_l3
              state: "on"
          sequence:
            - service: input_number.set_value
              target:
                entity_id: input_number.vr_baie_planned_position
              data:
                value: 0
            - service: input_text.set_value
              target:
                entity_id: input_text.vr_baie_condition
              data:
                value: "Condition : Home Cinema (sub) - 0 %" 


        # - conditions:
        #     - condition: state
        #       entity_id: binary_sensor.vr_sun_hot
        #       state: "on"
        #     - condition: state
        #       entity_id: binary_sensor.soleil_sud
        #       state: "on"
        #   sequence:
        #     - service: input_number.set_value
        #       target:
        #         entity_id: input_number.vr_baie_planned_position
        #       data:
        #         value: "{{ states('input_number.vr_global_position_sun_alert') }}"
        #     - service: input_text.set_value
        #       target:
        #         entity_id: input_text.vr_baie_condition
        #       data:
        #         value: "Condition : Ensoleillement excessif - {{ input_number.vr_global_position_sun_alert') }}%"

        # - conditions:
        #     - condition: state
        #       entity_id: binary_sensor.vr_sun_hot
        #       state: "on"
        #     - condition: state
        #       entity_id: binary_sensor.soleil_est
        #       state: "on"
        #   sequence:
        #     - service: input_number.set_value
        #       target:
        #         entity_id: input_number.vr_baie_planned_position
        #       data:
        #         value: "{{ states('input_number.vr_global_position_sun') }}"
        #     - service: input_text.set_value
        #       target:
        #         entity_id: input_text.vr_baie_condition
        #       data:
        #         value: "Condition : Ensoleillement fort - {{ states('input_number.vr_global_position_sun') }}%"


        - conditions:
            - condition: state
              entity_id: input_select.period_of_day
              state: "Nuit"
          sequence:
            - service: input_number.set_value
              target:
                entity_id: input_number.vr_baie_planned_position
              data:
                value: 0
        - conditions:
            - condition: state
              entity_id: input_select.vr_baie_immediate
              state: "Entrouvert"
          sequence:
            - service: input_number.set_value
              target:
                entity_id: input_number.vr_baie_planned_position
              data:
                value: "{{ states('input_number.vr_global_position_entrouvert') }}" # A faire
      default:
        - choose: # On vérifie si une routine correspond
            - conditions:
                - condition: numeric_state # On ferme le volet si le soleil est sous l'horizon
                  entity_id: sun.sun
                  attribute: elevation
                  below: 0
                - condition: state
                  entity_id: cover.vr_baie
                  state: "open"                  
              sequence:
                - service: input_number.set_value
                  target:
                    entity_id: input_number.vr_baie_planned_position
                  data:
                    value: "0"
                - service: input_text.set_value
                  target:
                    entity_id: input_text.vr_baie_condition
                  data:
                    value: "Action par défaut : Le soleil est couché - 0 %"

            - conditions:
                - condition: numeric_state # On ouvre le volet si le soleil est au dessus de l'horizon
                  entity_id: sun.sun
                  attribute: elevation
                  above: 0
                - condition: time
                  after: "13:00:00"
                # - condition: state
                #   entity_id: cover.vr_baie
                #   state: "closed"
              sequence:
                - service: input_number.set_value
                  target:
                    entity_id: input_number.vr_baie_planned_position
                  data:
                    value: "93"
                - service: input_text.set_value
                  target:
                    entity_id: input_text.vr_baie_condition
                  data:
                    value: "Action par défaut : Il est plus de 13:00, le soleil est levé - 93 %"

