input_boolean:
  lionel_up_down:
    name: Couché / Levé
    icon: mdi:toggle-switch
  vr_evening:
    name: Validation du mode soirée
    icon: mdi:toggle-switch


input_button:
  lionel_up:
    name: Je me lève
    icon: mdi:human-greeting-variant
  lionel_down:
    name: Je me couche
    icon: mdi:bed

input_number:
  vr_global_position_entrouvert:
    name: Position - Entrouverte
    min: "0"
    max: "100"
    step: "1"
    unit_of_measurement: "%"
    icon: mdi:swap-vertical
  vr_global_position_sun_alert:
    name: Position - Ensoleillement excessif
    min: "0"
    max: "100"
    step: "1"
    unit_of_measurement: "%"
    icon: mdi:swap-vertical
  vr_global_position_sun:
    name: Position - Ensoleillement
    min: "0"
    max: "100"
    step: "1"
    unit_of_measurement: "%"
    icon: mdi:swap-vertical
  vr_global_position_alarm:
    name: Position - Alarme
    min: "0"
    max: "100"
    step: "1"
    unit_of_measurement: "%"
    icon: mdi:swap-vertical
  vr_global_position_reveil:
    name: Position - Réveil
    min: "0"
    max: "100"
    step: "1"
    unit_of_measurement: "%"
    icon: mdi:swap-vertical
  vr_global_position_soir:
    name: Position - Soir
    min: "0"
    max: "100"
    step: "1"
    unit_of_measurement: "%"
    icon: mdi:swap-vertical

input_select:
  period_of_day:
    name: Nycthémère
    icon: mdi:theme-light-dark
    options:
      - Jour
      - Nuit
      - Nuit (Chambres)

automation:
- id: a800970c-9bf4-48ce-a26f-a67c29093eb3
  description: Change input_select.roller_shutter
  alias: VR - Global - Mode Automatique - change_input_select_roller_shutter
  mode: restart
  trigger:
    - platform: state
      entity_id: input_select.period_of_day
  action:
    - service: input_select.select_option
      target:
        entity_id:
          - input_select.vr_cuisine_immediate
          - input_select.vr_marie_immediate
          - input_select.vr_baie_immediate
          - input_select.vr_sejour_immediate
          - input_select.vr_antoine_immediate
          - input_select.vr_lionel_immediate
      data:
        option: Automatique

- id: a800880c-9df4-4fce-as6f-a67c24593eb3
  description: Change input_select.roller_shutter
  alias: VR - Global - Mode Manuel - change_input_select_roller_shutter
  mode: restart
  trigger:
    - platform: state
      entity_id: input_select.period_of_day
  action:
    - service: input_select.select_option
      target:
        entity_id:
          - input_select.vr_cuisine_immediate
          - input_select.vr_marie_immediate
          - input_select.vr_baie_immediate
          - input_select.vr_sejour_immediate
          - input_select.vr_antoine_immediate
          - input_select.vr_lionel_immediate
      data:
        option: Manuel

- id: a800970c-9bf4-48ce-aedg-a67c49093eb3
  description: Change vr_marie_immediate
  alias: VR - Global - Change mode - Présence Marie
  mode: restart
  trigger:
    - platform: state
      entity_id: input_boolean.presence_marie
  action:
    # - condition: template # Le volet ne doit pas être en mode "Manuel"
    #   value_template: "{{ not is_state('input_select.vr_marie_immediate', 'Manuel') }}"
    - choose: # On vérifie si une condition immédiate correspond
        - conditions:
            - condition: state
              entity_id: input_boolean.presence_marie
              state: "on"
          sequence:
            - service: input_select.select_option
              target:
                entity_id:
                  - input_select.vr_marie_immediate
              data:
                option: Manuel
        - conditions:
            - condition: state
              entity_id: input_boolean.presence_marie
              state: "off"
          sequence:
            - service: input_select.select_option
              target:
                entity_id:
                  - input_select.vr_marie_immediate
              data:
                option: Automatique

- id: a800970c-9bf4-48rf-aedg-a67c49093eb3
  description: Change vr_antoine_immediate
  alias: VR - Global - Change mode - Présence Antoine
  mode: restart
  trigger:
    - platform: state
      entity_id: input_boolean.presence_antoine
  action:
    - choose:
        - conditions:
            - condition: state
              entity_id: input_boolean.presence_antoine
              state: "on"
          sequence:
            - service: input_select.select_option
              target:
                entity_id:
                  - input_select.vr_antoine_immediate
              data:
                option: Manuel
        - conditions:
            - condition: state
              entity_id: input_boolean.presence_antoine
              state: "off"
          sequence:
            - service: input_select.select_option
              target:
                entity_id:
                  - input_select.vr_antoine_immediate
              data:
                option: Automatique





# - id: 5db664b4-6181-41ea-bf10-25c53cc43df1
#   description: VR Global - Timers - Save
#   alias: covers_timers_save
#   mode: queued
#   max: 20
#   trigger:
#     - platform: state
#       entity_id:
#         - timer.vr_cuisine # À modifier
#   action:
#     - service: input_text.set_value
#       data:
#         entity_id: "input_text.{{ trigger.entity_id.split('.')[1] }}_suspend"
#         value: "{{ (as_timestamp(state_attr(trigger.entity_id, 'finishes_at')) | int) if states(trigger.entity_id) == 'active' else ''}}"
#     - condition: template
#       value_template: "{{ states(trigger.entity_id) == 'idle' }}"
#     - service: automation.trigger
#       data:
#         skip_condition: false
#       target:
#         entity_id: "automation.{{ trigger.entity_id.split('.')[1] }}_position"        

# - id: f625f2fd-7d10-438e-bac5-3222d10ff340
#   description: VR Global - Timers - Restore
#   alias: covers_timers_restore
#   mode: single
#   trigger:
#     - platform: homeassistant
#       event: start
#   action:
#     - variables:
#         input_texts: "{{ states.input_text | map(attribute='entity_id') | list }}"
#     - repeat:
#         count: "{{ input_texts | count }}"
#         sequence:
#           - condition: template
#             value_template: "{{ input_texts[repeat.index-1].endswith('_suspend') }}"
#           - condition: template
#             value_template: "{{ is_number(states(input_texts[repeat.index-1])) }}"
#           - variables:
#               duration: "{{ (states(input_texts[repeat.index-1]) | int) - (as_timestamp(now()) | int) }}"
#           - choose:
#               - conditions: "{{ duration > 0 }}"
#                 sequence:
#                   - service: timer.start
#                     data:
#                       entity_id: "timer.{{ input_texts[repeat.index-1].split('.')[1].replace('_suspend', '') }}"
#                       duration: "{{ duration }}"
#             default:
#               - service: input_text.set_value
#                 data:
#                   entity_id: "{{ input_texts[repeat.index-1] }}"
#                   value: ""        